---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: finops
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - finops.krateo.io
  resources:
  - databaseconfigs
  verbs:
  - create
  - get
  - update
- apiGroups:
  - finops.krateo.io
  resources:
  - scraperconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - finops.krateo.io
  resources:
  - scraperconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - finops.krateo.io
  resources:
  - scraperconfigs/status
  verbs:
  - get
  - patch
  - update
