# permissions for end users to edit scraperconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scraperconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-scraper
    app.kubernetes.io/part-of: operator-scraper
    app.kubernetes.io/managed-by: kustomize
  name: scraperconfig-editor-role
rules:
- apiGroups:
  - finops.krateo.io
  resources:
  - scraperconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - finops.krateo.io
  resources:
  - scraperconfigs/status
  verbs:
  - get
